# Generated by Django 5.0.7 on 2024-07-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nodes', models.IntegerField()),
                ('weight_min', models.IntegerField()),
                ('weight_max', models.IntegerField()),
                ('start_node', models.IntegerField()),
                ('tour', models.TextField()),
                ('tour_cost', models.FloatField()),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
    ]
